spring.application.name=frotaBackEnd
api.security.token.secret=${JWT_SECRET:suXd42tATzbN/ewjV6NVY0Ug2edcOGSpLYctfxS7tLE=}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=joaopauloor21
spring.datasource.url=jdbc:mysql://localhost:3306/agrotrack_db
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true